name = "IOUtils"
uuid = "6aa5b9b4-0a87-4d01-8444-b9736d377f28"
authors = ["Stefanos Carlstr√∂m <stefanos.carlstrom@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[targets]
test = ["Test", "LinearAlgebra"]
